const mongoose = require('mongoose');

const customerSchema = new mongoose.Schema({
  name: { type: String, required: true }, // Customer's name
  email: { type: String, required: true, unique: true }, // Customer's email
  address: {
    street: { type: String, required: true }, // Street address
    city: { type: String, required: true }, // City
    state: { type: String, required: true }, // State
    zipCode: { type: String, required: true }, // Zip code
  },
  phone: { type: String, required: true, unique: true }, // Customer's phone number
  status: { type: String, enum: ['Active', 'Inactive'], default: 'Active' }, // Customer's status
  companyName: { type: String, required: true }, // Associated company name
  incomeGenerated: { type: Number, default: 0 }, // Total income generated by the customer
}, {
  timestamps: true, // Automatically add createdAt and updatedAt fields
});

module.exports = mongoose.model('Customer', customerSchema);